#ifndef __PH_H__
#define __PH_H__

#include <QApplication>
#include <QItemDelegate>
#include <QModelIndex>
#include <QCheckBox>
#include <QHBoxLayout>
#include <QPainter>
#include <QAbstractTableModel>
#include <QVariant>
#include <QSharedPointer>
#include <QVector>
#include <QMessageBox>
#include <QPixmap>
#include <QObject>
#include <QSize>
#include <QComboBox>
#include <QString>
#include <QLibrary>
#include <QtWidgets>
#include <QDir>
#include <QSortFilterProxyModel>
#include <QList>
#include <QTabWidget>
#include <QTableView>
#include <QMenu>
#include <QHeaderView>
#include <QTreeView>
#include <QFile>
#include <QTextStream>
#include <QDateTime>
#include <QtXml>
#include <QAbstractItemModel>
#include <QMimeData>
#include <QDataStream>
#include <QWeakPointer>
#include <QEnableSharedFromThis>
#include <QTranslator>
#include <QKeyEvent>
#include <QDebug>
#include <QFont>
#include <QSqlQuery>
#include <QSqlTableModel>
#include <QSettings>
#include <QSqlRelationalTableModel>
#include <QSqlError>

#endif // __PH_H__